language: java
jdk:
  - openjdk11

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_6cbc0ec7ad20_key -iv $encrypted_6cbc0ec7ad20_iv -in .travis/secret_keys.gpg.enc -out .travis/secret_keys.gpg -d
  - gpg --import .travis/secret_keys.gpg

deploy:
  provider: script
  script: "mvn -settings .travis/settings.xml -B -V clean deploy"
  skip_cleanup: true

